apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goldbach
  namespace: default
spec:
  secretName: goldbach
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: goldbach.9e315da9-05f3-4198-b1f5-895e7f0236c6.lb.civo.com
  dnsNames:
  - goldbach.9e315da9-05f3-4198-b1f5-895e7f0236c6.lb.civo.com