kind: Deployment
apiVersion: apps/v1
metadata:
  name: malaapp-dep
  namespace: default
  labels:
    app: malaapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malaapp-dep
  template:
    metadata:
      labels:
        app: malaapp-dep
    spec:
      containers:
      - name: malaapp
        image: "stamenium/zadatak:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: malaapp-dep
  namespace: default
spec:
  selector:
    app: malaapp-dep
  ports:
  - name: http
    targetPort: 11000
    port: 80